"""added followers table

Revision ID: f3287c4f26d0
Revises: a0820a5c2d3d
Create Date: 2018-03-29 19:07:28.561627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3287c4f26d0'
down_revision = 'a0820a5c2d3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artist_followers',
    sa.Column('follower_user', sa.Integer(), nullable=True),
    sa.Column('followed_artist', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_artist'], ['artist.id'], ),
    sa.ForeignKeyConstraint(['follower_user'], ['user.uid'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('artist_followers')
    # ### end Alembic commands ###
